# Generated by Django 5.1.1 on 2024-09-15 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='OrderCustomer',
        ),
        migrations.RenameModel(
            old_name='Product',
            new_name='OrderItems',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='updated',
            new_name='last_updated',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='order_customer',
        ),
        migrations.RenameField(
            model_name='orderitems',
            old_name='price',
            new_name='price_per_unit',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Received'), (2, 'Processing'), (3, 'Payment complete'), (4, 'Shipping'), (5, 'Completed'), (6, 'Cancelled')], default='1'),
        ),
    ]
